apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: dtdemoslides
  name: dtdemoslides
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    run: dtdemoslides
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dtdemoslides
  name: dtdemoslides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtdemoslides
  strategy: {}
  template:
    metadata:
      labels:
        app: dtdemoslides
    spec:
      containers:
      - image: domuharahap/dtdemoslides:v1
        name: dtdemoslides
        resources: {}
status: {}

