apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dtslides
  name: dtslides
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: dtslides
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dtslides
  name: dtslides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtslides
  strategy: {}
  template:
    metadata:
      labels:
        app: dtslides
    spec:
      containers:
      - image: domuharahap/dtslides:latest
        name: dtslides
        resources: {}
status: {}

